# SPDX-FileCopyrightText:  Copyright © 2022 The Fern Authors <team@fernproxy.io>
# SPDX-License-Identifier: Apache-2.0

version: "3.8"

services:
  fern-proxy:
    image: fern-proxy:latest
    container_name: fern-proxy
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - target: 30000
        published: 30000
        protocol: tcp
        mode: overlay
    networks:
      - with-fern-proxy
    depends_on:
      - postgres-server

  postgres-server:
    image: postgres
    container_name: postgres-server
    restart: always
    networks:
      - with-fern-proxy
    environment:
      - POSTGRES_DB=testdb
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=testpassword


networks:
  with-fern-proxy:
