# SPDX-FileCopyrightText:  Copyright © 2022 The Fern Authors <team@fernproxy.io>
# SPDX-License-Identifier: Apache-2.0

version: "3.8"

services:
  fern-proxy:
    image: fern-proxy:dev
    build:
      target: dev-env
    ports:
      - target: 30000
        published: 30000
        protocol: tcp
        mode: overlay

  postgres-client:
    image: postgres
    container_name: postgres-client
    command: /bin/bash -c 'while true; do echo POSTGRES CLIENT is up; sleep 60; done'
    networks:
      - with-fern-proxy
